- hosts: target
  vars_files: ../vars.yml
  tasks:
    - name: install prerequisites
      action: apt pkg=$item state=latest
      with_items:
        - python-dev
        - mysql-server
        - mysql-client
        - python-mysqldb
        - libmysqlclient-dev
- hosts: target
  vars_files:
    - ../vars.yml
  sudo: yes
  sudo_user: mysql
  tasks:
    - name: setup db
      mysql_db: db=sentry state=present
    - name: setup user
      mysql_user: name=sentry password=sentry priv=sentry.*:ALL state=present
  handlers:
    - include: handlers.yml
